### ISSUE TITLE
Paramétrer l'application 

### ISSUE THREAD

**Issue by JereDacosta** [JereDacosta/oxygen-cs-grp1-eq9#2]
Pour bien tester le pipeline d’intégration continue créer à l’étape 3, il vous est demandé d’apporter la 
modification suivante à votre projet : paramétrer l’application à l’aide de variables d’environnement. 
Dans l’application de base, il y a 4 variables qui pourraient être paramétrées pour faciliter la configuration 
selon les besoins et l’environnement. 

Si la variable d’environnement n’est pas définie, vous devez avoir une valeur par défaut. Si le token n’est 
pas défini en variable d'environnement, l'application doit retourner une erreur. Pour toute modification 
du code, vous devez ajouter un ensemble des tests unitaires en lien.

**Comment by MathieuSevignyLavallee** [comment]
Les parametre son implementé. Il manque seulement de les mettre par défault
